inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge: Exclude

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma